# =============================================================================
# GitHub Issue Template 전역 설정
# =============================================================================

# 빈 이슈 생성 금지 - 모든 이슈는 템플릿을 사용해야 함
# 이렇게 하면 모든 이슈가 Bug Report 또는 Feature Request 템플릿을 사용하게 됨
blank_issues_enabled: false
